# Generated by Django 2.0 on 2019-11-30 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('escore_news', models.IntegerField(verbose_name='Escore_news')),
                ('frequencia', models.CharField(max_length=255, verbose_name='Frequencia de controle')),
                ('resposta', models.CharField(max_length=512, verbose_name='Resposta Clinica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('telefone', models.IntegerField(blank=True, null=True, verbose_name='Telefone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=16, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nivel_conciencia', models.CharField(blank=True, max_length=2, null=True, verbose_name='Nivel_conciencia')),
                ('temperatura', models.FloatField(blank=True, null=True, verbose_name='Temperatura')),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True, verbose_name='Frequencia_cardiaca')),
                ('pa_sistolica', models.IntegerField(blank=True, null=True, verbose_name='Pa_sistoliza')),
                ('frequencia_respiratoria', models.IntegerField(blank=True, null=True, verbose_name='Frequencia_respiratoria')),
                ('saturacao_oxigenio', models.IntegerField(blank=True, null=True, verbose_name='Saturacao_de_oxigenio')),
                ('qualquer_o2', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Nao')], max_length=2, null=True, verbose_name='Qualquer_suplemacao_o2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pacientes', to='score.Score'),
        ),
    ]
