# Generated by Django 2.0 on 2019-12-02 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-criado_em']},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='score',
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Nome_da_mae'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='valor_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='valor_score'),
        ),
        migrations.AddField(
            model_name='score',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='score.Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='score',
            name='frequencia_cardiaca',
            field=models.IntegerField(blank=True, default=51, null=True, verbose_name='Frequencia_cardiaca'),
        ),
        migrations.AlterField(
            model_name='score',
            name='frequencia_respiratoria',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Frequencia_respiratoria'),
        ),
        migrations.AlterField(
            model_name='score',
            name='nivel_conciencia',
            field=models.CharField(blank=True, choices=[('A', 'Alerta'), ('V', 'Voz'), ('D', 'Dor'), ('NR', 'Nao responde')], default='A', max_length=2, null=True, verbose_name='Nivel_conciencia'),
        ),
        migrations.AlterField(
            model_name='score',
            name='pa_sistolica',
            field=models.IntegerField(blank=True, default=111, null=True, verbose_name='Pa_sistoliza'),
        ),
        migrations.AlterField(
            model_name='score',
            name='qualquer_o2',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Nao')], default='S', max_length=2, null=True, verbose_name='Qualquer_suplemacao_o2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='saturacao_oxigenio',
            field=models.IntegerField(blank=True, default=96, null=True, verbose_name='Saturacao_de_oxigenio'),
        ),
        migrations.AlterField(
            model_name='score',
            name='temperatura',
            field=models.FloatField(blank=True, default=36.1, null=True, verbose_name='Temperatura'),
        ),
    ]
