# Generated by Django 2.0 on 2019-12-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_paciente_leito'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='score.Perfil'),
        ),
        migrations.AlterField(
            model_name='score',
            name='qualquer_o2',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=2, null=True, verbose_name='Qualquer_suplemacao_o2'),
        ),
    ]
